Architecture: "drought-lstm"

Seed: 42

Setting: "drought"

Logger:
    save_dir: "experiments/"

Checkpointer:
    save_top_k: 1
    save_last: True
    every_n_epochs: 1

Trainer:
    devices: 1 #6
    strategy: 'ddp'
    #deterministic: True
    log_every_n_steps: 32
    #profiler: 'advanced'
    fast_dev_run: False
    #log_gpu_memory: 'all'
    #weights_summary: 'full'
    max_epochs: 1
    #limit_train_batches: 32
    #limit_val_batches: 32
    gradient_clip_val: 1
    #val_check_interval: 0.1 #val after fraction of training epoch
    check_val_every_n_epoch: 1
    num_sanity_val_steps: 0
    #overfit_batches: 0.0
  
Data:
    base_dir: "/Users/led/Desktop/New code/" #where data is stored
    #test_track: "iid"
    train_batch_size: 4 #96
    val_batch_size: 4
    test_batch_size: 4 #96
    num_workers: 8
    #dl_cloudmask: True

Task:
    loss:
        name: "L2NDVILoss"
        ndvi_pred_idx: 0
        ndvi_targ_idx: 16
    context_length: 3 #55 (9 months)
    target_length: 2 #20 (3 months)
    optimization:
        optimizer:
            - 
                name: Adam
                args: 
                    betas: [0.9, 0.999] 
                lr_per_sample: 0.000001
        lr_shedule:
            -
                name: MultiStepLR
                args:
                    milestones: [160,190] #[2, 20, 50, 90]
                    gamma: 0.1
    n_log_batches: 2
    #compute_metric_on_test: True

Model:
    input_dim: 20 #number of input features
    hidden_dim: 32 #number of nodes in hidden layers
    num_layers: 2 #number of hidden layers
    target_length: 2
