Architecture: drought-lstm
Checkpointer:
  every_n_epochs: 1
  monitor: RMSE_drought
  save_last: true
  save_top_k: 1
Data:
  base_dir: /Users/selene/Desktop/New code/
  num_workers: 8
  test_batch_size: 4
  test_track: iid
  train_batch_size: 4
  val_batch_size: 4
Logger:
  save_dir: experiments/
Model:
  hidden_dim: 64
  input_dim: 16
  num_layers: 6
  target_length: 1
Seed: 42
Setting: drought
Task:
  compute_metric_on_test: true
  context_length: 1
  loss:
    name: L2NDVILoss
    ndvi_pred_idx: 0
    ndvi_targ_idx: 13
  n_log_batches: 2
  optimization:
    lr_shedule:
    - args:
        gamma: 0.1
        milestones:
        - 160
        - 190
      name: MultiStepLR
    optimizer:
    - args:
        betas:
        - 0.8
        - 0.999
        lr: 0.0001
      lr_per_sample: 1.0e-06
      name: Adam
  target_length: 1
Trainer:
  check_val_every_n_epoch: 1
  devices: 1
  fast_dev_run: false
  gradient_clip_val: 1
  log_every_n_steps: 32
  max_epochs: 1
  num_sanity_val_steps: 0
  strategy: ddp
